"""APKPEEK - zero-install Android APK / manifest security analyzer (MobSF-style).

Decodes a real .apk (ZIP), a binary AndroidManifest.xml (compiled AXML) or a
plain-text manifest and runs a bundled rule pack covering exported components,
dangerous/signature permissions, debuggable & allowBackup flags, cleartext
traffic and hard-coded secret strings. Standard library only.
"""

from .core import (
    TOOL_NAME,
    TOOL_VERSION,
    SEVERITY_ORDER,
    PERMISSION_CATALOG,
    HIGH_RISK_PERMISSIONS,
    SECRET_RULES,
    SECRET_STOPWORDS,
    SecretRule,
    Engine,
    Finding,
    Component,
    Manifest,
    Report,
    XmlElement,
    shannon_entropy,
    is_binary_axml,
    decode_binary_axml,
    decode_binary_axml_full,
    parse_manifest_from_elements,
    parse_manifest_text,
    manifest_from_bytes,
    analyze,
    analyze_apk,
    analyze_manifest_file,
    sort_findings,
    summarize,
    _strip_android_prefix,
)

__all__ = [
    "TOOL_NAME",
    "TOOL_VERSION",
    "SEVERITY_ORDER",
    "PERMISSION_CATALOG",
    "HIGH_RISK_PERMISSIONS",
    "SECRET_RULES",
    "SECRET_STOPWORDS",
    "SecretRule",
    "Engine",
    "Finding",
    "Component",
    "Manifest",
    "Report",
    "XmlElement",
    "shannon_entropy",
    "is_binary_axml",
    "decode_binary_axml",
    "decode_binary_axml_full",
    "parse_manifest_from_elements",
    "parse_manifest_text",
    "manifest_from_bytes",
    "analyze",
    "analyze_apk",
    "analyze_manifest_file",
    "sort_findings",
    "summarize",
]
